[2024-04-30T08:58:49.914+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T08:58:49.946+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v4.connect_to_database manual__2024-04-30T08:44:45.732115+00:00 [queued]>
[2024-04-30T08:58:49.955+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v4.connect_to_database manual__2024-04-30T08:44:45.732115+00:00 [queued]>
[2024-04-30T08:58:49.956+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 11
[2024-04-30T08:58:49.973+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): connect_to_database> on 2024-04-30 08:44:45.732115+00:00
[2024-04-30T08:58:49.985+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v4', 'connect_to_database', 'manual__2024-04-30T08:44:45.732115+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmpaiicsjdx']
[2024-04-30T08:58:49.986+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3648) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T08:58:49.988+0000] {standard_task_runner.py:91} INFO - Job 292: Subtask connect_to_database
[2024-04-30T08:58:49.988+0000] {standard_task_runner.py:63} INFO - Started process 3661 to run task
[2024-04-30T08:58:50.037+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v4.connect_to_database manual__2024-04-30T08:44:45.732115+00:00 [running]> on host 37e9c82bc18f
[2024-04-30T08:58:50.157+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v4' AIRFLOW_CTX_TASK_ID='connect_to_database' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T08:44:45.732115+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T08:44:45.732115+00:00'
[2024-04-30T08:58:50.161+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T08:58:50.425+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T08:58:50.426+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T08:58:50.437+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=tweets_dag_v4, task_id=connect_to_database, execution_date=20240430T084445, start_date=20240430T085849, end_date=20240430T085850
[2024-04-30T08:58:50.484+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T08:58:50.505+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T08:58:50.508+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
