[2024-04-26T14:02:20.247+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T14:02:20.308+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres.create_postgres_table scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-26T14:02:20.328+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres.create_postgres_table scheduled__2024-04-11T00:00:00+00:00 [queued]>
[2024-04-26T14:02:20.329+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-26T14:02:20.358+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2024-04-11 00:00:00+00:00
[2024-04-26T14:02:20.370+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=525) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T14:02:20.373+0000] {standard_task_runner.py:63} INFO - Started process 530 to run task
[2024-04-26T14:02:20.370+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres', 'create_postgres_table', 'scheduled__2024-04-11T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpht5h6i74']
[2024-04-26T14:02:20.376+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask create_postgres_table
[2024-04-26T14:02:20.462+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres.create_postgres_table scheduled__2024-04-11T00:00:00+00:00 [running]> on host 0ceb125076fc
[2024-04-26T14:02:20.638+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='dag_with_postgres' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-11T00:00:00+00:00'
[2024-04-26T14:02:20.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T14:02:20.665+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
        
[2024-04-26T14:02:20.680+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-26T14:02:20.694+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-26T14:02:20.711+0000] {sql.py:457} INFO - Running statement: 
            CREATE TABLE if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
        , parameters: None
[2024-04-26T14:02:20.720+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/common/sql/hooks/sql.py:407 AirflowProviderDeprecationWarning: Call to deprecated method _make_common_data_structure. (The `_make_serializable` method is deprecated and support will be removed in a future version of the common.sql provider. Please update the DbApiHook's provider to a version based on common.sql >= 1.9.1.)
[2024-04-26T14:02:20.725+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T14:02:20.741+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres, task_id=create_postgres_table, execution_date=20240411T000000, start_date=20240426T140220, end_date=20240426T140220
[2024-04-26T14:02:20.789+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T14:02:20.816+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T14:02:20.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
