[2024-04-26T14:33:52.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T14:33:52.995+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag.init_tweets_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-04-26T14:33:53.089+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag.init_tweets_db scheduled__2024-03-24T00:00:00+00:00 [queued]>
[2024-04-26T14:33:53.112+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-26T14:33:53.201+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): init_tweets_db> on 2024-03-24 00:00:00+00:00
[2024-04-26T14:33:53.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag', 'init_tweets_db', 'scheduled__2024-03-24T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmpkm_sq5n3']
[2024-04-26T14:33:53.263+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask init_tweets_db
[2024-04-26T14:33:53.269+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2572) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T14:33:53.276+0000] {standard_task_runner.py:63} INFO - Started process 2580 to run task
[2024-04-26T14:33:53.529+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag.init_tweets_db scheduled__2024-03-24T00:00:00+00:00 [running]> on host 0ceb125076fc
[2024-04-26T14:33:53.980+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag' AIRFLOW_CTX_TASK_ID='init_tweets_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-24T00:00:00+00:00'
[2024-04-26T14:33:53.985+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T14:33:54.070+0000] {sql.py:276} INFO - Executing: CREATE TABLE positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

[2024-04-26T14:33:54.148+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-04-26T14:33:54.194+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-04-26T14:33:54.248+0000] {sql.py:457} INFO - Running statement: CREATE TABLE positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);
, parameters: None
[2024-04-26T14:33:54.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T14:33:54.283+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: relation "positive_tweets" already exists

[2024-04-26T14:33:54.345+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag, task_id=init_tweets_db, execution_date=20240324T000000, start_date=20240426T143352, end_date=20240426T143354
[2024-04-26T14:33:54.409+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 124 for task init_tweets_db (relation "positive_tweets" already exists
; 2580)
[2024-04-26T14:33:54.464+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T14:33:54.511+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T14:33:54.525+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
