[2024-04-30T08:43:51.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T08:43:51.225+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v3.execute_python_script manual__2024-04-30T08:43:02.735744+00:00 [queued]>
[2024-04-30T08:43:51.237+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v3.execute_python_script manual__2024-04-30T08:43:02.735744+00:00 [queued]>
[2024-04-30T08:43:51.238+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 7
[2024-04-30T08:43:51.257+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): execute_python_script> on 2024-04-30 08:43:02.735744+00:00
[2024-04-30T08:43:51.272+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v3', 'execute_python_script', 'manual__2024-04-30T08:43:02.735744+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmp4f6tbbce']
[2024-04-30T08:43:51.276+0000] {standard_task_runner.py:91} INFO - Job 275: Subtask execute_python_script
[2024-04-30T08:43:51.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1924) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-30T08:43:51.279+0000] {standard_task_runner.py:63} INFO - Started process 1977 to run task
[2024-04-30T08:43:51.354+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v3.execute_python_script manual__2024-04-30T08:43:02.735744+00:00 [running]> on host 37e9c82bc18f
[2024-04-30T08:43:51.474+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v3' AIRFLOW_CTX_TASK_ID='execute_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T08:43:02.735744+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T08:43:02.735744+00:00'
[2024-04-30T08:43:51.476+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T08:44:36.770+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-04-30T08:44:37.012+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-30T08:44:37.025+0000] {process_utils.py:132} INFO - Sending 15 to group 1977. PIDs of all processes in the group: [1977]
[2024-04-30T08:44:37.030+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1977
[2024-04-30T08:44:37.032+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-30T08:44:37.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T08:44:37.048+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_transform.py", line 50, in roberta_classifier
    output = model(**encoded_text)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 1191, in forward
    outputs = self.roberta(
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 828, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 517, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 406, in forward
    self_attention_outputs = self.attention(
                             ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 333, in forward
    self_outputs = self.self(
                   ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/transformers/models/roberta/modeling_roberta.py", line 212, in forward
    key_layer = self.transpose_for_scores(self.key(hidden_states))
                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-30T08:44:37.057+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag_v3, task_id=execute_python_script, execution_date=20240430T084302, start_date=20240430T084351, end_date=20240430T084437
[2024-04-30T08:44:37.076+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 275 for task execute_python_script ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(tweets_dag_v3, execute_python_script, manual__2024-04-30T08:43:02.735744+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'execute_python_script', 'dag_id': 'tweets_dag_v3', 'run_id': 'manual__2024-04-30T08:43:02.735744+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 4, 30, 8, 43, 51, 225694, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 4, 30, 8, 44, 37, 56394, tzinfo=Timezone('UTC')), 'duration': 45}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1977)
[2024-04-30T08:44:37.165+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1977, status='terminated', exitcode=1, started='08:43:50') (1977) terminated with exit code 1
